"""empty message

Revision ID: fa2e07fd3804
Revises: aee151fd7c4a
Create Date: 2022-05-19 12:30:37.315536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2e07fd3804'
down_revision = 'aee151fd7c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logo_url', sa.String(length=64), nullable=True))
    op.drop_column('user', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logo', sa.BLOB(), nullable=True))
    op.drop_column('user', 'logo_url')
    # ### end Alembic commands ###
